### ISSUE TITLE
Introduction of Bitcoin sidechain

### ISSUE THREAD

**Issue by pixelplex** [peerplays-network/pips#3]
The intent behind introduction of Bitcoin sidechain is to provide a way for PeerPlays users to perform operations with an analogue of Bitcoin within the current and to-be-developed applications.

The intent of this issue is to initiate the process of creating a PeerPlays Improvement Proposal, which will have the motivation for Bitcoin sidechain, as well as the description for the functionality and mechanisms introduced with it.

**Comment by pixelplex** [comment]
@xeroc could you please consider opening a PIP for this issue, as per the general process?

**Comment by xeroc** [comment]
@pixelplex the general process is described [here](https://github.com/peerplays-network/pips/blob/master/pip-0001.md).

Usually, you take the [template](https://github.com/peerplays-network/pips/blob/master/template.md) and publish it as an issue for discussion here.
